databaseChangeLog:
  - changeSet:
      id: 004-create-applications-table
      author: fleksi-team
      changes:
        - createTable:
            tableName: applications
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: shift_id
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: user_id
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: varchar(20)
                  constraints:
                    nullable: false
                  defaultValue: 'APPLIED'
              - column:
                  name: created_at
                  type: timestamp with time zone
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp with time zone
                  constraints:
                    nullable: false