/* tslint:disable */
/* eslint-disable */
/**
 * Fleksi API
 * API-first specification for Fleksi platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@fleksi.pl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/system-api';

