version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fleksi-postgres
    environment:
      POSTGRES_DB: fleksi
      POSTGRES_USER: fleksi
      POSTGRES_PASSWORD: fleksi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fleksi -d fleksi"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fleksi-network

  redis:
    image: redis:7-alpine
    container_name: fleksi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - fleksi-network

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: fleksi-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - fleksi-network
    profiles:
      - tools

  # Optional: pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fleksi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fleksi.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fleksi-network
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  fleksi-network:
    driver: bridge