spring:
  application:
    name: fleksi-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/fleksi
    username: fleksi
    password: fleksi
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    pl.com.aseity: DEBUG
    org.springframework.security: DEBUG